### ISSUE TITLE
WARNING: Duplicate explicit target name: "binder"

### ISSUE THREAD

**Issue by bast** [AaltoSciComp/python-for-scicomp#32]
This is because there are two links in `binder.rst` with the same name pointing to the same web address.

This is one thing that I find annoying about Sphinx/RST and don't understand the reasoning. What is the workaround for this other than renaming it?

**Comment by rkdarst** [comment]
I think this can be solved by ending the links with `__` instead of
`_`.  Took me a while to figure this out.

Why: `binder <http://...>`_ breaks this into a refererence: "binder ->
https://" .  So that later, you could do `connect to binder
<binder_>`_ and it would dereference it to that.  A similar syntax:

```
Connect to `binder`_

.. _binder: https://...
```

Or this:
```
Connect to `the website <binder_>`_

.. _binder: https://...
```

(in the second case, you can define it once and use it many times).
Somehow, these are related to the error we see.

**Comment by bast** [comment]
Thanks for explanation! I can see that this can be useful but I find it super annoying. The frequent thing should be easy and the shortcuts should be possible but here the shortcut stuff makes the frequent thing annoying.

**Comment by bast** [comment]
I will send a patch for this.

**Comment by rkdarst** [comment]
I just made the patch too.
On Fri, Sep 11, 2020 at 05:14:34AM -0700, Radovan Bast wrote:
> I will send a patch for this.

-- 
| Richard Darst   -   http://rkd.zgib.net/   -   pgp 0xBD356740
| "Ye shall know the truth and -- the truth shall make you free"
